on: [pull_request, push]
name: Hata kontrolü ve lint
jobs:
  lint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then grep -v py7zr requirements.txt > req2.txt && pip install -r req2.txt; fi
          if [ -f requirements-gui.txt ]; then pip install -r requirements-gui.txt; else pip install PyQt6; fi
          pip install pylint
      - name: Run pylint (errors only quick scan)
        shell: bash
        run: |
          shopt -s globstar
          pylint --ignored-modules py7zr -E **/*.py || true
      - name: Run pylint (package strict)
        shell: bash
        run: |
          pylint --ignored-modules py7zr turkanime_api/ --fail-under 8.2
      - name: Run pylint (script optional)
        shell: bash
        run: |
          if [ -f turkanime.py ]; then pylint --ignored-modules py7zr turkanime.py --fail-under 9.2; fi
