name: PyPI Publish

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/turkanime-gui
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry poetry-dynamic-versioning
      - name: Build packages
        run: |
          poetry-dynamic-versioning
          poetry build
          sed -i 's/name = "turkanime-gui"/name = "turkanime-cli"/' pyproject.toml
          sed -i 's/turkanime_api.gui:main/turkanime_api.cli:main/' pyproject.toml
          poetry build
      - name: Publish packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          skip-existing: true
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
